//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.12 at 10:14:28 AM IST 
//


package tns.wpg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="returnMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="merchantResponse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="merchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acquirerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acquirerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maskCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardExpiry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "returnCode",
        "returnMessage",
        "transID",
        "merchantResponse",
        "merchantID",
        "value",
        "acquirerID",
        "acquirerName",
        "bankID",
        "bankName",
        "maskedCardNumber",
        "cardExpiry",
        "merchantReference",
        "authTransID",
        "operation",
        "vendorID",
        "timestamp"
})
@XmlRootElement(name = "tokenSettleResponse", namespace = "tns:wpg")
public class TokenSettleResponse {

    @XmlElement(required = true)
    protected String returnCode;
    @XmlElement(required = true)
    protected String returnMessage;
    @XmlElement(required = true)
    protected String transID;
    @XmlElement(required = true)
    protected String merchantResponse;
    @XmlElement(required = true)
    protected String merchantID;
    @XmlElement(required = true)
    protected String value;
    @XmlElement(required = true)
    protected String acquirerID;
    @XmlElement(required = true)
    protected String acquirerName;
    @XmlElement(required = true)
    protected String bankID;
    @XmlElement(required = true)
    protected String bankName;
    @XmlElement(required = true)
    protected String maskedCardNumber;
    @XmlElement(required = true)
    protected String cardExpiry;
    @XmlElement(required = true)
    protected String merchantReference;
    @XmlElement(required = true)
    protected String authTransID;
    @XmlElement(required = true)
    protected String operation;
    @XmlElement(required = true)
    protected String vendorID;
    @XmlElement(required = true)
    protected String timestamp;

    /**
     * Gets the value of the returnCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the returnMessage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReturnMessage() {
        return returnMessage;
    }

    /**
     * Sets the value of the returnMessage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReturnMessage(String value) {
        this.returnMessage = value;
    }

    /**
     * Gets the value of the transID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransID() {
        return transID;
    }

    /**
     * Sets the value of the transID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransID(String value) {
        this.transID = value;
    }

    /**
     * Gets the value of the merchantResponse property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMerchantResponse() {
        return merchantResponse;
    }

    /**
     * Sets the value of the merchantResponse property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMerchantResponse(String value) {
        this.merchantResponse = value;
    }

    /**
     * Gets the value of the merchantID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the acquirerID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcquirerID() {
        return acquirerID;
    }

    /**
     * Sets the value of the acquirerID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcquirerID(String value) {
        this.acquirerID = value;
    }

    /**
     * Gets the value of the acquirerName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcquirerName() {
        return acquirerName;
    }

    /**
     * Sets the value of the acquirerName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcquirerName(String value) {
        this.acquirerName = value;
    }

    /**
     * Gets the value of the bankID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBankID() {
        return bankID;
    }

    /**
     * Sets the value of the bankID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBankID(String value) {
        this.bankID = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBankName(String value) {
        this.bankName = value;
    }


    /**
     * Gets the value of the cardExpiry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCardExpiry() {
        return cardExpiry;
    }

    /**
     * Sets the value of the cardExpiry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCardExpiry(String value) {
        this.cardExpiry = value;
    }

    public String getMaskedCardNumber() {
        return maskedCardNumber;
    }

    public void setMaskedCardNumber(String maskedCardNumber) {
        this.maskedCardNumber = maskedCardNumber;
    }

    public String getMerchantReference() {
        return merchantReference;
    }

    public void setMerchantReference(String merchantReference) {
        this.merchantReference = merchantReference;
    }

    public String getAuthTransID() {
        return authTransID;
    }

    public void setAuthTransID(String authTransID) {
        this.authTransID = authTransID;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public String getVendorID() {
        return vendorID;
    }

    public void setVendorID(String vendorID) {
        this.vendorID = vendorID;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "TokenSettleResponse{" +
                "returnCode='" + returnCode + '\'' +
                ", returnMessage='" + returnMessage + '\'' +
                ", transID='" + transID + '\'' +
                ", merchantResponse='" + merchantResponse + '\'' +
                ", merchantID='" + merchantID + '\'' +
                ", value='" + value + '\'' +
                ", acquirerID='" + acquirerID + '\'' +
                ", acquirerName='" + acquirerName + '\'' +
                ", bankID='" + bankID + '\'' +
                ", bankName='" + bankName + '\'' +
                ", maskedCardNumber='" + maskedCardNumber + '\'' +
                ", cardExpiry='" + cardExpiry + '\'' +
                ", merchantReference='" + merchantReference + '\'' +
                ", authTransID='" + authTransID + '\'' +
                ", operation='" + operation + '\'' +
                ", vendorID='" + vendorID + '\'' +
                ", timestamp='" + timestamp + '\'' +
                '}';
    }
}
